// place 1河流 2大海 3河口 4池塘 5高地水域 6码头 7大海(雨天)
// shape 1略小 2小 3中 4大 5略大 6特大 7细长 8背鳍
// time 1全天  2 9-16  3 16-9  4 4-21  5 21-4  6 9-16&21-4

const config = [
  {
    id: 1, // 编号
    name: '红目鲫', // 名称
    eng_name: 'Bitterling',
    jap_name: 'タナゴ',
    price: 900, // 价格
    place: 1, // 地点
    shape: 1, // 鱼影
    month_n: [1, 2, 3, 11, 12], // 北半球
    month_s: [5, 6, 7, 8, 9], // 南半球
    time: 1, // 时间
  },
  {
    id: 2,
    name: '溪哥',
    eng_name: 'Pale chub',
    jap_name: 'オイカワ',
    price: 200,
    place: 1,
    shape: 1,
    month_n: [],
    month_s: [],
    time: 2,
  },
  {
    id: 3,
    name: '鲫鱼',
    eng_name: 'Crucian carp',
    jap_name: 'フナ',
    price: 160,
    place: 1,
    shape: 2,
    month_n: [],
    month_s: [],
    time: 1,
  },
  {
    id: 4,
    name: '雅罗鱼',
    eng_name: 'Dace',
    jap_name: 'ウグイ',
    price: 240,
    place: 1,
    shape: 3,
    month_n: [],
    month_s: [],
    time: 3,
  },
  {
    id: 5,
    name: '鲤鱼',
    eng_name: 'Carp',
    jap_name: 'コイ',
    price: 300,
    place: 4,
    shape: 5,
    month_n: [],
    month_s: [],
    time: 1,
  },
  {
    id: 6,
    name: '锦鲤',
    eng_name: 'Koi',
    jap_name: 'ニシキゴイ',
    price: 4000,
    place: 4,
    shape: 5,
    month_n: [],
    month_s: [],
    time: 3,
  },
  {
    id: 7,
    name: '金鱼',
    eng_name: 'Goldfish',
    jap_name: 'キンギョ',
    price: 1300,
    place: 4,
    shape: 1,
    month_n: [],
    month_s: [],
    time: 1,
  },
  {
    id: 8,
    name: '龙睛金鱼',
    eng_name: 'Pop-eyed goldfish',
    jap_name: 'デメキン',
    price: 1300,
    place: 4,
    shape: 1,
    month_n: [],
    month_s: [],
    time: 2,
  },
  {
    id: 9,
    name: '兰寿金鱼',
    eng_name: 'Ranchu goldfish',
    jap_name: 'ランチュウ',
    price: 4500,
    place: 4,
    shape: 2,
    month_n: [],
    month_s: [],
    time: 2,
  },
  {
    id: 10,
    name: '稻田鱼',
    eng_name: 'Killifish',
    jap_name: 'メダカ',
    price: 300,
    place: 4,
    shape: 1,
    month_n: [4, 5, 6, 7, 8],
    month_s: [1, 2, 10, 11, 12],
    time: 1,
  },
  {
    id: 11,
    name: '淡水龙虾',
    eng_name: 'Crawfish',
    jap_name: 'ザリガニ',
    price: 200,
    place: 4,
    shape: 2,
    month_n: [4, 5, 6, 7, 8, 9],
    month_s: [1, 2, 3, 10, 11, 12],
    time: 1,
  },
  {
    id: 12,
    name: '鳖',
    eng_name: 'Soft-shelled turtle',
    jap_name: 'スッポン',
    price: 3750,
    place: 1,
    shape: 5,
    month_n: [8, 9],
    month_s: [2, 3],
    time: 3,
  },
  {
    id: 13,
    name: '拟鳄龟',
    eng_name: 'Snapping turtle',
    jap_name: 'カミツキガメ	',
    price: 5000,
    place: 1,
    shape: 5,
    month_n: [4, 5, 6, 7, 8, 9, 10],
    month_s: [1, 2, 3, 4, 10, 11, 12],
    time: 5,
  },
  {
    id: 14,
    name: '蝌蚪',
    eng_name: 'Tadpole',
    jap_name: 'オタマジャクシ',
    price: 100,
    place: 4,
    shape: 1,
    month_n: [3, 4, 5, 6, 7],
    month_s: [1, 9, 10, 11, 12],
    time: 1,
  },
  {
    id: 15,
    name: '青蛙',
    eng_name: 'Frog',
    jap_name: 'カエル',
    price: 120,
    place: 4,
    shape: 2,
    month_n: [5, 6, 7, 8],
    month_s: [1, 2, 10, 11, 12],
    time: 1,
  },
  {
    id: 16,
    name: '塘鳢鱼',
    eng_name: 'Freshwater goby',
    jap_name: 'ドンコ',
    price: 400,
    place: 1,
    shape: 2,
    month_n: [],
    month_s: [],
    time: 3,
  },
  {
    id: 17,
    name: '泥鳅',
    eng_name: 'Loach',
    jap_name: 'ドジョウ',
    price: 400,
    place: 1,
    shape: 2,
    month_n: [3, 4, 5],
    month_s: [9, 10, 11],
    time: 1,
  },
  {
    id: 18,
    name: '鲶鱼',
    eng_name: 'Catfish',
    jap_name: 'ナマズ',
    price: 800,
    place: 4,
    shape: 5,
    month_n: [5, 6, 7, 8, 9, 10],
    month_s: [1, 2, 3, 4, 11, 12],
    time: 3,
  },
  {
    id: 19,
    name: '黑鱼',
    eng_name: 'Giant snakehead',
    jap_name: 'ライギョ',
    price: 5500,
    place: 4,
    shape: 5,
    month_n: [6, 7, 8],
    month_s: [1, 2, 12],
    time: 2,
  },
  {
    id: 20,
    name: '蓝腮太阳鱼',
    eng_name: 'Bluegill',
    jap_name: 'ブルーギル',
    price: 180,
    place: 1,
    shape: 2,
    month_n: [],
    month_s: [],
    time: 2,
  },
  {
    id: 21,
    name: '黄鲈鱼',
    eng_name: 'Yellow perch',
    jap_name: 'イエローパーチ',
    price: 300,
    place: 1,
    shape: 3,
    month_n: [1, 2, 3, 10, 11, 12],
    month_s: [4, 5, 6, 7, 8, 9],
    time: 1,
  },
  {
    id: 22,
    name: '黑鲈鱼',
    eng_name: 'Black bass',
    jap_name: 'ブラックバス',
    price: 400,
    place: 1,
    shape: 5,
    month_n: [],
    month_s: [],
    time: 1,
  },
  {
    id: 23,
    name: '吴郭鱼',
    eng_name: 'Tilapia',
    jap_name: 'ティラピア',
    price: 800,
    place: 1,
    shape: 3,
    month_n: [6, 7, 8, 9, 10],
    month_s: [1, 2, 3, 4, 12],
    time: 1,
  },
  {
    id: 24,
    name: '白斑狗鱼',
    eng_name: 'Pike',
    jap_name: 'パイク',
    price: 1800,
    place: 1,
    shape: 6,
    month_n: [9, 10, 11, 12],
    month_s: [3, 4, 5, 6],
    time: 1,
  },
  {
    id: 25,
    name: '西太公鱼',
    eng_name: 'Pond smelt',
    jap_name: 'ワカサギ',
    price: 500,
    place: 1,
    shape: 2,
    month_n: [1, 2, 12],
    month_s: [6, 7, 8],
    time: 1,
  },
  {
    id: 26,
    name: '香鱼',
    eng_name: 'Sweetfish',
    jap_name: 'アユ',
    price: 900,
    place: 1,
    shape: 3,
    month_n: [7, 8, 9],
    month_s: [1, 2, 3],
    time: 1,
  },
  {
    id: 27,
    name: '樱花钩吻鲑',
    eng_name: 'Cherry salmon',
    jap_name: 'ヤマメ',
    price: 1000,
    place: 5,
    shape: 3,
    month_n: [3, 4, 5, 6, 9, 10, 11],
    month_s: [3, 4, 5, 9, 10, 11, 12],
    time: 3,
  },
  {
    id: 28,
    name: '花羔红点鲑',
    eng_name: 'Char',
    jap_name: 'オオイワナ',
    price: 3800,
    place: 5,
    shape: 3,
    month_n: [3, 4, 5, 6, 9, 10, 11],
    month_s: [3, 4, 5, 9, 10, 11, 12],
    time: 3,
  },
  {
    id: 29,
    name: '金鳟',
    eng_name: 'Golden trout',
    jap_name: 'ゴールデントラウト',
    price: 15000,
    place: 5,
    shape: 3,
    month_n: [3, 4, 5, 6, 9, 10, 11],
    month_s: [3, 4, 5, 9, 10, 11, 12],
    time: 3,
  },
  {
    id: 30,
    name: '远东哲罗鱼',
    eng_name: 'Stringfish',
    jap_name: 'イトウ',
    price: 15000,
    place: 5,
    shape: 6,
    month_n: [1, 2, 3, 12],
    month_s: [6, 7, 8, 9],
    time: 3,
  },
  {
    id: 31,
    name: '鲑鱼',
    eng_name: 'Salmon',
    jap_name: 'サケ',
    price: 700,
    place: 3,
    shape: 5,
    month_n: [9],
    month_s: [3],
    time: 1,
  },
  {
    id: 32,
    name: '帝王鲑',
    eng_name: 'King salmon',
    jap_name: 'キングサーモン',
    price: 1800,
    place: 3,
    shape: 6,
    month_n: [9],
    month_s: [3],
    time: 1,
  },
  {
    id: 33,
    name: '中华绒螯蟹',
    eng_name: 'Mitten crab',
    jap_name: 'シャンハイガニ',
    price: 2000,
    place: 1,
    shape: 2,
    month_n: [9, 10, 11],
    month_s: [3, 4, 5],
    time: 3,
  },
  {
    id: 34,
    name: '孔雀鱼',
    eng_name: 'Guppy',
    jap_name: 'グッピー',
    price: 1300,
    place: 1,
    shape: 1,
    month_n: [4, 5, 6, 7, 8, 9, 10, 11],
    month_s: [1, 2, 3, 4, 5, 10, 11, 12],
    time: 2,
  },
  {
    id: 35,
    name: '温泉医生鱼',
    eng_name: 'Nibble fish',
    jap_name: 'ドクターフィッシュ',
    price: 1500,
    place: 1,
    shape: 1,
    month_n: [5, 6, 7, 8, 9],
    month_s: [1, 2, 3, 11, 12],
    time: 2,
  },
  {
    id: 36,
    name: '神仙鱼',
    eng_name: 'Angelfish',
    jap_name: 'エンゼルフィッシュ',
    price: 3000,
    place: 1,
    shape: 2,
    month_n: [5, 6, 7, 8, 9, 10],
    month_s: [1, 2, 3, 4, 11, 12],
    time: 3,
  },
  {
    id: 37,
    name: '斗鱼',
    eng_name: 'Betta',
    jap_name: 'ベタ',
    price: 2500,
    place: 1,
    shape: 2,
    month_n: [5, 6, 7, 8, 9, 10],
    month_s: [1, 2, 3, 4, 11, 12],
    time: 2,
  },
  {
    id: 38,
    name: '霓虹灯鱼',
    eng_name: 'Neon tetra',
    jap_name: 'ネオンテトラ',
    price: 500,
    place: 1,
    shape: 1,
    month_n: [4, 5, 6, 7, 8, 9, 10, 11],
    month_s: [1, 2, 3, 4, 5, 10, 11, 12],
    time: 2,
  },
  {
    id: 39,
    name: '彩虹鱼',
    eng_name: 'Rainbowfish',
    jap_name: 'レインボーフィッシュ',
    price: 800,
    place: 1,
    shape: 1,
    month_n: [5, 6, 7, 8, 9, 10],
    month_s: [1, 2, 3, 4, 11, 12],
    time: 2,
  },
  {
    id: 40,
    name: '食人鱼',
    eng_name: 'Piranha',
    jap_name: 'ピラニア',
    price: 2500,
    place: 1,
    shape: 2,
    month_n: [6, 7, 8, 9],
    month_s: [1, 2, 3, 12],
    time: 6,
  },
  {
    id: 41,
    name: '骨舌鱼',
    eng_name: 'Arowana',
    jap_name: 'アロワナ',
    price: 10000,
    place: 1,
    shape: 5,
    month_n: [6, 7, 8, 9],
    month_s: [1, 2, 3, 12],
    time: 3,
  },
  {
    id: 42,
    name: '黄金河虎',
    eng_name: 'Dorado',
    jap_name: 'ドラド',
    price: 15000,
    place: 1,
    shape: 6,
    month_n: [6, 7, 8, 9],
    month_s: [1, 2, 3, 12],
    time: 4,
  },
  {
    id: 43,
    name: '雀鳝',
    eng_name: 'Gar',
    jap_name: 'ガー',
    price: 6000,
    place: 4,
    shape: 6,
    month_n: [6, 7, 8, 9],
    month_s: [1, 2, 3, 12],
    time: 3,
  },
  {
    id: 44,
    name: '巨骨舌鱼',
    eng_name: 'Arapaima',
    jap_name: 'ピラルク',
    price: 10000,
    place: 1,
    shape: 7,
    month_n: [6, 7, 8, 9],
    month_s: [1, 2, 3, 12],
    time: 3,
  },
  {
    id: 45,
    name: '恩氏多鳍鱼',
    eng_name: 'Saddled bichir',
    jap_name: 'エンドリケリー',
    price: 4000,
    place: 1,
    shape: 5,
    month_n: [6, 7, 8, 9],
    month_s: [1, 2, 3, 12],
    time: 5,
  },
  {
    id: 46,
    name: '鲟鱼',
    eng_name: 'Sturgeon',
    jap_name: 'チョウザメ',
    price: 10000,
    place: 3,
    shape: 7,
    month_n: [1, 2, 3, 9, 10, 11, 12],
    month_s: [3, 4, 5, 6, 7, 8, 9],
    time: 1,
  },
  {
    id: 47,
    name: '海蝴蝶',
    eng_name: 'Sea butterfly',
    jap_name: 'クリオネ',
    price: 1000,
    place: 2,
    shape: 1,
    month_n: [1, 2, 3, 12],
    month_s: [6, 7, 8, 9],
    time: 1,
  },
  {
    id: 48,
    name: '海马',
    eng_name: 'Seahorse',
    jap_name: 'タツノオトシゴ',
    price: 1100,
    place: 2,
    shape: 1,
    month_n: [4, 5, 6, 7, 8, 9, 10, 11],
    month_s: [1, 2, 3, 4, 5, 10, 11, 12],
    time: 1,
  },
  {
    id: 49,
    name: '小丑鱼',
    eng_name: 'Clownfish',
    jap_name: 'クマノミ',
    price: 650,
    place: 2,
    shape: 1,
    month_n: [4, 5, 6, 7, 8, 9],
    month_s: [1, 2, 3, 10, 11, 12],
    time: 1,
  },
  {
    id: 50,
    name: '拟刺尾鲷',
    eng_name: 'Surgeonfish',
    jap_name: 'ナンヨウハギ	',
    price: 1000,
    place: 2,
    shape: 2,
    month_n: [4, 5, 6, 7, 8, 9],
    month_s: [1, 2, 3, 10, 11, 12],
    time: 1,
  },
  {
    id: 51,
    name: '耳带蝴蝶鱼',
    eng_name: 'Butterfly fish',
    jap_name: 'チョウチョウウオ',
    price: 1000,
    place: 2,
    shape: 2,
    month_n: [4, 5, 6, 7, 8, 9],
    month_s: [1, 2, 3, 10, 11, 12],
    time: 1,
  },
  {
    id: 52,
    name: '苏眉鱼',
    eng_name: 'Napoleonfish',
    jap_name: 'ナポレオンフィッシュ',
    price: 10000,
    place: 2,
    shape: 7,
    month_n: [7, 8],
    month_s: [1, 2],
    time: 4,
  },
  {
    id: 53,
    name: '狮子鱼',
    eng_name: 'Zebra turkeyfish',
    jap_name: 'ミノカサゴ',
    price: 500,
    place: 2,
    shape: 3,
    month_n: [4, 5, 6, 7, 8, 9, 10, 11],
    month_s: [1, 2, 3, 4, 5, 10, 11, 12],
    time: 1,
  },
  {
    id: 54,
    name: '河豚',
    eng_name: 'Blowfish',
    jap_name: 'フグ',
    price: 5000,
    place: 2,
    shape: 3,
    month_n: [1, 2, 11, 12],
    month_s: [5, 6, 7, 8],
    time: 5,
  },
  {
    id: 55,
    name: '刺豚',
    eng_name: 'Puffer fish',
    jap_name: 'ハリセンボン',
    price: 250,
    place: 2,
    shape: 3,
    month_n: [7, 8, 9],
    month_s: [1, 2, 3],
    time: 1,
  },
  {
    id: 56,
    name: '凤尾鱼',
    eng_name: 'Anchovy',
    jap_name: 'アンチョビ',
    price: 200,
    place: 2,
    shape: 2,
    month_n: [],
    month_s: [],
    time: 4,
  },
  {
    id: 57,
    name: '竹荚鱼',
    eng_name: 'Horse mackerel',
    jap_name: 'アジ',
    price: 150,
    place: 2,
    shape: 2,
    month_n: [],
    month_s: [],
    time: 1,
  },
  {
    id: 58,
    name: '条石鲷',
    eng_name: 'Barred knifejaw',
    jap_name: 'イシダイ',
    price: 5000,
    place: 2,
    shape: 3,
    month_n: [3, 4, 5, 6, 7, 8, 9, 10, 11],
    month_s: [1, 2, 3, 4, 5, 9, 10, 11, 12],
    time: 1,
  },
  {
    id: 59,
    name: '鲈鱼',
    eng_name: 'Sea bass',
    jap_name: 'スズキ',
    price: 400,
    place: 2,
    shape: 6,
    month_n: [],
    month_s: [],
    time: 1,
  },
  {
    id: 60,
    name: '鲷鱼',
    eng_name: 'Red snapper',
    jap_name: 'タイ',
    price: 3000,
    place: 2,
    shape: 5,
    month_n: [],
    month_s: [],
    time: 1,
  },
  {
    id: 61,
    name: '鲽鱼',
    eng_name: 'Dab',
    jap_name: 'カレイ',
    price: 300,
    place: 2,
    shape: 3,
    month_n: [1, 2, 3, 4, 10, 11, 12],
    month_s: [4, 5, 6, 7, 8.9, 10],
    time: 1,
  },
  {
    id: 62,
    name: '比目鱼',
    eng_name: 'Olive flounder',
    jap_name: 'ヒラメ',
    price: 800,
    place: 2,
    shape: 6,
    month_n: [],
    month_s: [],
    time: 1,
  },
  {
    id: 63,
    name: '鱿鱼',
    eng_name: 'Squid',
    jap_name: 'イカ',
    price: 500,
    place: 2,
    shape: 3,
    month_n: [1, 2, 3, 4, 5, 6, 7, 8, 12],
    month_s: [1, 2, 6, 7, 8, 9, 10, 11, 12],
    time: 1,
  },
  {
    id: 64,
    name: '裸胸鳝',
    eng_name: 'Moray eel',
    jap_name: 'ウツボ',
    price: 2000,
    place: 2,
    shape: 8,
    month_n: [8, 9, 10],
    month_s: [2, 3, 4],
    time: 1,
  },
  {
    id: 65,
    name: '五彩鳗',
    eng_name: 'Ribbon eel',
    jap_name: 'ハナヒゲウツボ',
    price: 600,
    place: 2,
    shape: 8,
    month_n: [6, 7, 8, 9, 10],
    month_s: [1, 2, 3, 4, 12],
    time: 1,
  },
  {
    id: 66,
    name: '鲔鱼',
    eng_name: 'Tuna',
    jap_name: 'マグロ',
    price: 7000,
    place: 6,
    shape: 7,
    month_n: [1, 2, 3, 4, 11, 12],
    month_s: [5, 6, 7, 8, 9, 10],
    time: 1,
  },
  {
    id: 67,
    name: '旗鱼',
    eng_name: 'Blue marlin',
    jap_name: 'カジキ',
    price: 10000,
    place: 6,
    shape: 7,
    month_n: [1, 2, 3, 4, 7, 8, 9, 11, 12],
    month_s: [1, 2, 3, 5, 6, 7, 8, 9, 10],
    time: 1,
  },
  {
    id: 68,
    name: '白面弄鱼',
    eng_name: 'Giant trevally',
    jap_name: 'ロウニンアジ',
    price: 4500,
    place: 6,
    shape: 6,
    month_n: [5, 6, 7, 8, 9, 10],
    month_s: [1, 2, 3, 4, 11, 12],
    time: 1,
  },
  {
    id: 69,
    name: '鬼头刀',
    eng_name: 'Mahi-mahi',
    jap_name: 'シイラ',
    price: 6000,
    place: 6,
    shape: 6,
    month_n: [5, 6, 7, 8, 9, 10],
    month_s: [1, 2, 3, 4, 11, 12],
    time: 1,
  },
  {
    id: 70,
    name: '翻车鱼',
    eng_name: 'Ocean sunfish',
    jap_name: 'マンボウ',
    price: 4000,
    place: 2,
    shape: 9,
    month_n: [7, 8, 9],
    month_s: [1, 2, 3],
    time: 4,
  },
  {
    id: 71,
    name: '鳐鱼',
    eng_name: 'Ray',
    jap_name: 'エイ',
    price: 3000,
    place: 2,
    shape: 6,
    month_n: [8, 9, 10, 11],
    month_s: [2, 3, 4, 5],
    time: 4,
  },
  {
    id: 72,
    name: '锯鲨',
    eng_name: 'Saw shark',
    jap_name: 'ノコギリザメ',
    price: 12000,
    place: 2,
    shape: 9,
    month_n: [6, 7, 8, 9],
    month_s: [1, 2, 3, 12],
    time: 3,
  },
  {
    id: 73,
    name: '双鬓鲨',
    eng_name: 'Hammerhead shark',
    jap_name: 'シュモクザメ',
    price: 8000,
    place: 2,
    shape: 9,
    month_n: [6, 7, 8, 9],
    month_s: [1, 2, 3, 12],
    time: 3,
  },
  {
    id: 74,
    name: '鲨鱼',
    eng_name: 'Great white shark',
    jap_name: 'サメ',
    price: 15000,
    place: 2,
    shape: 9,
    month_n: [6, 7, 8, 9],
    month_s: [1, 2, 3, 12],
    time: 3,
  },
  {
    id: 75,
    name: '鲸鲨',
    eng_name: 'Whale shark',
    jap_name: 'ジンベイザメ',
    price: 13000,
    place: 2,
    shape: 9,
    month_n: [6, 7, 8, 9],
    month_s: [1, 2, 3, 12],
    time: 1,
  },
  {
    id: 76,
    name: '吸盘鱼',
    eng_name: 'Suckerfish',
    jap_name: 'コバンザメ',
    price: 1500,
    place: 2,
    shape: 9,
    month_n: [6, 7, 8, 9],
    month_s: [1, 2, 3, 12],
    time: 1,
  },
  {
    id: 77,
    name: '灯笼鱼',
    eng_name: 'Football fish',
    jap_name: 'チョウチンアンコウ',
    price: 2500,
    place: 2,
    shape: 5,
    month_n: [1, 2, 3, 11, 12],
    month_s: [5, 6, 7, 8, 9],
    time: 3,
  },
  {
    id: 78,
    name: '皇带鱼',
    eng_name: 'Oarfish',
    jap_name: 'リュウグウノツカイ',
    price: 9000,
    place: 2,
    shape: 7,
    month_n: [1, 2, 3, 4, 5, 12],
    month_s: [6, 7, 8, 9, 10, 11],
    time: 1,
  },
  {
    id: 79,
    name: '太平洋桶眼鱼',
    eng_name: 'Barreleye',
    jap_name: 'デメニギス',
    price: 15000,
    place: 2,
    shape: 2,
    month_n: [],
    month_s: [],
    time: 5,
  },
  {
    id: 80,
    name: '矛尾鱼',
    eng_name: 'Coelacanth',
    jap_name: 'シーラカンス',
    price: 15000,
    place: 7,
    shape: 7,
    month_n: [],
    month_s: [],
    time: 1,
  },
];

export default config;
